name = "job-application-worker"
main = "src/index.js"
compatibility_date = "2025-03-03"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "metana"
database_id = "d91f03a7-bced-4c6e-97e9-6613041326de"

# R2 Bucket Configuration
[[r2_buckets]]
binding = "metana"
bucket_name = "metana"

# Environment Variables
[vars]
DEBUG = "true"